name: pull-request
on:
  push:
  pull_request:
    branches: [ develop, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: npm install
      - name: Code check
        run: npm run lint

