name: pull-request
on:
  pull_request:
    branches: [ develop, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8.1.1
      - name: Install dependencies
        run: pnpm install
      - name: Verify code quality
        run: pnpm run lint
      - name: Run tests
        run: pnpm test

